#!/bin/bash
# Copyright (c) 2013, Igor Novikov
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

cd "$( dirname "${BASH_SOURCE[0]}" )"

issue="$1"
description="$2"
description_lowercase=`echo "$description" | tr '[:upper:]' '[:lower:]' | sed 's/[^A-Za-z0-9]/-/g' | sed 's/--\+/-/g'`
date=`date -Idate`
user=`whoami`
file="$description_lowercase-$issue.xml"

sed -i "s/<\/databaseChangeLog>/    <include relativeToChangelogFile="'"'"true"'"'" file="'"'"$file"'"'" \/>\n\0/g" history/_all.xml

cp history/_template.xml history/$file
sed -i "s/@ISSUE@/$issue/g" history/$file
sed -i "s/@USER@/$user/g" history/$file
sed -i "s/@DATE@/$date/g" history/$file
sed -i "s/@DESCRIPTION@/$description/g" history/$file

vim history/$file
