#!/bin/bash
# Copyright (c) 2013, Igor Novikov
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

cd "$( dirname "${BASH_SOURCE[0]}" )"

LIQUIBASE_VERSION=3.0.5

function get_config_var {
    php -r "require_once ('../config.php'); echo "'$config'" ['database'] ['$1'];";
}

HOSTNAME=`get_config_var host`
USERNAME=`get_config_var user`
PASSWORD=`get_config_var pass`
DATABASE=`get_config_var name`

java \
    -classpath ../3rdparty/snakeyaml-1.13.jar:../3rdparty/liquibase-$LIQUIBASE_VERSION.jar \
    liquibase.integration.commandline.Main \
    --classpath=../3rdparty/mysql-connector-java-5.1.22-bin.jar \
    --driver=com.mysql.jdbc.Driver \
    --changeLogFile=history/_all.xml \
    --url="jdbc:mysql://$HOSTNAME/$DATABASE" \
    --username="$USERNAME" \
    --password="$PASSWORD" \
    update
